import type { ActivityEvent, Asset, Dataset, SecurityGapDefinition, Vulnerability } from "./types"

/**
 * Simulated demonstration dataset. Nothing here is sourced from real systems.
 * Replace with backend API responses that satisfy the same interfaces.
 */

export const SIMULATED_BASE_TIME = "2026-10-09T08:30:00+05:30"

export const initialAssets: Asset[] = [
  {
    id: "a-pay-prod",
    name: "Payment Production Server",
    type: "Application Server",
    owner: "Payments Engineering",
    criticality: "Critical",
    exposure: "Internet-facing",
    threatEvidence: 0.85,
    openHighSeverityIncidents: 2,
    openVulnerabilityCount: 23,
    controls: { mfa: "Partial", edr: "Partial", patching: "Missing", segmentation: "Missing", backup: "Active" },
  },
  {
    id: "a-cust-db",
    name: "Customer Database",
    type: "Database",
    owner: "Data Platform",
    criticality: "Critical",
    exposure: "Internal",
    threatEvidence: 0.75,
    openHighSeverityIncidents: 0,
    openVulnerabilityCount: 14,
    controls: { mfa: "Active", edr: "Partial", patching: "Partial", segmentation: "Missing", backup: "Partial" },
  },
  {
    id: "a-idp",
    name: "Corporate Identity Server",
    type: "Identity Server",
    owner: "IAM Team",
    criticality: "Critical",
    exposure: "Internal",
    threatEvidence: 0.9,
    openHighSeverityIncidents: 1,
    openVulnerabilityCount: 11,
    controls: { mfa: "Missing", edr: "Partial", patching: "Missing", segmentation: "Missing", backup: "Active" },
  },
  {
    id: "a-pay-api",
    name: "Payment API Gateway",
    type: "API Gateway",
    owner: "Payments Engineering",
    criticality: "Critical",
    exposure: "Internet-facing",
    threatEvidence: 0.8,
    openHighSeverityIncidents: 0,
    openVulnerabilityCount: 9,
    controls: { mfa: "Active", edr: "Active", patching: "Missing", segmentation: "Partial", backup: "Active" },
  },
  {
    id: "a-vpn",
    name: "Corporate VPN Concentrator",
    type: "Network Appliance",
    owner: "Network Operations",
    criticality: "Critical",
    exposure: "Internet-facing",
    threatEvidence: 0.75,
    openHighSeverityIncidents: 1,
    openVulnerabilityCount: 8,
    controls: { mfa: "Partial", edr: "Unavailable", patching: "Active", segmentation: "Partial", backup: "Active" },
  },
  {
    id: "a-backup",
    name: "Backup Infrastructure",
    type: "Backup System",
    owner: "Infrastructure",
    criticality: "Critical",
    exposure: "Internal",
    threatEvidence: 0.4,
    openHighSeverityIncidents: 0,
    openVulnerabilityCount: 10,
    controls: { mfa: "Partial", edr: "Missing", patching: "Partial", segmentation: "Partial", backup: "Missing" },
  },
  {
    id: "a-partner-hub",
    name: "Partner Integration Hub",
    type: "Integration Hub",
    owner: "Integration Services",
    criticality: "Critical",
    exposure: "Partner network",
    threatEvidence: 0.35,
    openHighSeverityIncidents: 0,
    openVulnerabilityCount: 12,
    controls: { mfa: "Active", edr: "Partial", patching: "Partial", segmentation: "Missing", backup: "Active" },
  },
  {
    id: "a-hr-app",
    name: "HR Application Server",
    type: "Application Server",
    owner: "People Systems",
    criticality: "High",
    exposure: "Internal",
    threatEvidence: 0.3,
    openHighSeverityIncidents: 0,
    openVulnerabilityCount: 16,
    controls: { mfa: "Missing", edr: "Partial", patching: "Missing", segmentation: "Partial", backup: "Active" },
  },
  {
    id: "a-mail",
    name: "Email Gateway",
    type: "Web Server",
    owner: "Messaging",
    criticality: "High",
    exposure: "Internet-facing",
    threatEvidence: 0.5,
    openHighSeverityIncidents: 0,
    openVulnerabilityCount: 7,
    controls: { mfa: "Active", edr: "Active", patching: "Active", segmentation: "Partial", backup: "Active" },
  },
  {
    id: "a-dev-ws",
    name: "Developer Workstation",
    type: "Workstation",
    owner: "Engineering IT",
    criticality: "Medium",
    exposure: "Internal",
    threatEvidence: 0.45,
    openHighSeverityIncidents: 0,
    openVulnerabilityCount: 21,
    controls: { mfa: "Partial", edr: "Missing", patching: "Partial", segmentation: "Missing", backup: "Partial" },
  },
  {
    id: "a-marketing",
    name: "Marketing Website",
    type: "Web Server",
    owner: "Digital Marketing",
    criticality: "Low",
    exposure: "Internet-facing",
    threatEvidence: 0.25,
    openHighSeverityIncidents: 0,
    openVulnerabilityCount: 9,
    controls: { mfa: "Active", edr: "Partial", patching: "Partial", segmentation: "Active", backup: "Active" },
  },
  {
    id: "a-wiki",
    name: "Internal Wiki",
    type: "Web Server",
    owner: "Engineering IT",
    criticality: "Low",
    exposure: "Internal",
    threatEvidence: 0.1,
    openHighSeverityIncidents: 0,
    openVulnerabilityCount: 6,
    controls: { mfa: "Active", edr: "Active", patching: "Partial", segmentation: "Active", backup: "Active" },
  },
]

function vuln(
  n: number,
  assetId: string,
  title: string,
  cvss: number,
  exploitStatus: Vulnerability["exploitStatus"],
  patchAvailable: boolean,
  lastAssessed: string,
  remediation: string,
): Vulnerability {
  return {
    id: `v-${n}`,
    demoId: `DEMO-2026-${String(n).padStart(4, "0")}`,
    title,
    assetId,
    cvss,
    exploitStatus,
    patchAvailable,
    remediated: false,
    lastAssessed,
    remediation,
  }
}

export const initialVulnerabilities: Vulnerability[] = [
  vuln(1, "a-pay-prod", "Remote code execution in payment web framework", 9.8, "Exploited (simulated intel)", true, "2026-10-09T06:10:00+05:30", "Apply vendor patch to payment web framework; restart service in maintenance window."),
  vuln(2, "a-pay-prod", "Outdated TLS library allows downgrade", 7.4, "Public PoC", true, "2026-10-09T06:10:00+05:30", "Upgrade TLS library and disable legacy cipher suites."),
  vuln(3, "a-pay-prod", "Verbose error pages disclose stack traces", 5.3, "None known", true, "2026-10-08T22:40:00+05:30", "Disable debug output in production configuration."),
  vuln(4, "a-cust-db", "Privilege escalation in database engine", 8.8, "Public PoC", true, "2026-10-09T05:00:00+05:30", "Upgrade database engine to the patched minor release."),
  vuln(5, "a-cust-db", "Default service account with weak password policy", 7.1, "None known", false, "2026-10-08T19:15:00+05:30", "Rotate service account credentials and enforce password policy."),
  vuln(6, "a-idp", "Authentication bypass in legacy SSO connector", 9.1, "Exploited (simulated intel)", true, "2026-10-09T04:30:00+05:30", "Patch SSO connector and decommission legacy protocol endpoint."),
  vuln(7, "a-idp", "LDAP injection in directory search", 6.5, "None known", true, "2026-10-08T21:05:00+05:30", "Apply input sanitisation patch to directory service."),
  vuln(8, "a-pay-api", "Request smuggling in reverse proxy", 8.1, "Public PoC", true, "2026-10-09T03:50:00+05:30", "Upgrade reverse proxy and normalise request parsing."),
  vuln(9, "a-pay-api", "Rate limiting not enforced on token endpoint", 5.9, "None known", false, "2026-10-08T18:20:00+05:30", "Configure rate limits on token issuance endpoint."),
  vuln(10, "a-vpn", "Pre-auth path traversal in VPN web portal", 9.0, "Exploited (simulated intel)", true, "2026-10-09T02:15:00+05:30", "Apply emergency firmware update; review portal access logs."),
  vuln(11, "a-backup", "Unauthenticated access to backup management API", 8.6, "None known", true, "2026-10-08T23:30:00+05:30", "Patch backup controller and restrict management API to admin network."),
  vuln(12, "a-backup", "Backup encryption keys stored alongside data", 6.8, "None known", false, "2026-10-08T17:45:00+05:30", "Move encryption keys to a dedicated key management service."),
  vuln(13, "a-partner-hub", "XML external entity processing in partner feed parser", 7.5, "Public PoC", true, "2026-10-08T20:10:00+05:30", "Disable external entity resolution in XML parser."),
  vuln(14, "a-hr-app", "SQL injection in employee search", 8.2, "Public PoC", true, "2026-10-08T16:30:00+05:30", "Apply application patch; use parameterised queries."),
  vuln(15, "a-hr-app", "Session tokens do not expire", 5.4, "None known", true, "2026-10-08T16:30:00+05:30", "Configure session expiry and idle timeout."),
  vuln(16, "a-mail", "Header injection in mail relay", 6.1, "None known", true, "2026-10-08T15:00:00+05:30", "Upgrade mail relay to patched version."),
  vuln(17, "a-dev-ws", "Unpatched browser with sandbox escape", 8.0, "Public PoC", true, "2026-10-08T14:25:00+05:30", "Force browser update through endpoint management."),
  vuln(18, "a-dev-ws", "Local admin rights granted to standard users", 6.3, "None known", false, "2026-10-08T14:25:00+05:30", "Remove local admin rights; use just-in-time elevation."),
  vuln(19, "a-marketing", "Outdated CMS plugin with stored XSS", 6.1, "Public PoC", true, "2026-10-08T12:00:00+05:30", "Update CMS plugin; enable content security policy."),
  vuln(20, "a-wiki", "Information disclosure in page history", 4.3, "None known", true, "2026-10-07T11:00:00+05:30", "Apply wiki platform update."),
]

export const initialDataset: Dataset = {
  assets: initialAssets,
  vulnerabilities: initialVulnerabilities,
}

export const securityGapDefinitions: SecurityGapDefinition[] = [
  {
    id: "gap-mfa",
    control: "mfa",
    title: "Missing MFA on a critical identity path",
    evidenceTemplate: "MFA control is not fully enforced",
    consequence: "Stolen or phished credentials could grant direct access to identity and payment systems, enabling account takeover and fraudulent transactions.",
    remediation: "Enforce phishing-resistant MFA on the identity provider, administrative accounts and remote access paths.",
  },
  {
    id: "gap-edr",
    control: "edr",
    title: "Incomplete endpoint detection coverage",
    evidenceTemplate: "EDR agent is missing, partial or unavailable",
    consequence: "Malicious activity on uncovered hosts may go undetected, extending attacker dwell time and delaying incident response.",
    remediation: "Deploy EDR agents to all servers and workstations; alert on agent health failures.",
  },
  {
    id: "gap-patching",
    control: "patching",
    title: "Critical patches overdue",
    evidenceTemplate: "Patch compliance is below SLA",
    consequence: "Known, exploitable weaknesses remain open on business-critical systems, the most common path to initial compromise.",
    remediation: "Prioritise patches for internet-facing critical assets with exploitable findings; enforce a 7-day SLA for critical fixes.",
  },
  {
    id: "gap-segmentation",
    control: "segmentation",
    title: "Weak network segmentation",
    evidenceTemplate: "Network segmentation is not enforced",
    consequence: "A single compromised host could move laterally to databases and payment infrastructure, increasing blast radius.",
    remediation: "Segment payment, data and identity tiers; restrict east-west traffic to explicitly approved flows.",
  },
  {
    id: "gap-backup",
    control: "backup",
    title: "Backup recovery testing overdue",
    evidenceTemplate: "Backup restore testing has not been validated",
    consequence: "Ransomware or data corruption could cause prolonged outage if backups cannot be restored within recovery objectives.",
    remediation: "Run quarterly restore tests for critical systems and isolate backup copies from production credentials.",
  },
]

export const initialActivity: ActivityEvent[] = [
  {
    id: "evt-1",
    at: "2026-10-09T08:30:00+05:30",
    kind: "assessment",
    title: "Risk assessment completed",
    description: "Scheduled assessment evaluated 12 assets and 146 open findings from the simulated dataset.",
    severity: "Info",
  },
  {
    id: "evt-2",
    at: "2026-10-09T07:55:00+05:30",
    kind: "risk-change",
    title: "Payment Production Server risk increased",
    description: "Simulated threat intelligence linked DEMO-2026-0001 to active exploitation; threat evidence raised to 0.85.",
    severity: "Critical",
    assetId: "a-pay-prod",
  },
  {
    id: "evt-3",
    at: "2026-10-09T06:10:00+05:30",
    kind: "vulnerability",
    title: "New vulnerability detected: DEMO-2026-0001",
    description: "Remote code execution (CVSS 9.8) identified on Payment Production Server.",
    severity: "Critical",
    assetId: "a-pay-prod",
  },
  {
    id: "evt-4",
    at: "2026-10-09T03:20:00+05:30",
    kind: "control",
    title: "EDR coverage marked unavailable",
    description: "Endpoint detection agent stopped reporting on Corporate VPN Concentrator.",
    severity: "High",
    assetId: "a-vpn",
  },
  {
    id: "evt-5",
    at: "2026-10-08T18:40:00+05:30",
    kind: "remediation",
    title: "Remediation recorded on Email Gateway",
    description: "Mail relay patched; patch compliance control set to Active.",
    severity: "Info",
    assetId: "a-mail",
  },
]

/** Simulated historical overall-risk scores for the six days before today. */
export const riskTrendHistory: { day: string; score: number }[] = [
  { day: "Oct 03", score: 69 },
  { day: "Oct 04", score: 71 },
  { day: "Oct 05", score: 70 },
  { day: "Oct 06", score: 73 },
  { day: "Oct 07", score: 74 },
  { day: "Oct 08", score: 76 },
]
